# Generated by Django 5.0.4 on 2024-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_active',
            field=models.SmallIntegerField(choices=[(0, 'ACTIVO'), (1, 'FINALIZADO'), (2, 'CANCELADO')], default=0),
        ),
    ]
